spring:
  application.name: object-service
  config:
    import: optional:configserver:http://localhost:8888
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5433/studs
    username: fost
    password: fost
    driver-class-name: org.postgresql.Driver

  minio:
    accessKey: "fost"
    secretKey: "fostfost"
    bucket: "makeit-photos"
    url: "http://127.0.0.1:9000"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/

server.port: 8090